### ISSUE TITLE
[Feature Suggestion] Built-in Vanilla Command Permission Nodes

### ISSUE THREAD

**Issue by Alkali-Metal** [Innectic/Permissify#1]
# What Will It Do?
It will allow for users to have Vanilla command limiters if they so desire to have them.

# Why This Would Be Awesomesauce:
Because all the plugins that have vanilla permission nodes are super convoluted or just flat out don't work, and having them built into the permissions plugin itself would be nice for just limiting the vanilla permissions without needing to get an extra 12 million commands from some stupid other plugin.

# How Would It Work:
Just have like `permissify.vanilla.<COMMAND>.[Sub Command]` or something like that and Permissify reads it.

**Comment by Innectic** [comment]
Great idea 👍

**Comment by Innectic** [comment]
I've decided that this is something that would bloat the plugin too much, closing.
